sudo: required

dist: xenial

language: python

python:
  - 3.7.2

services:
  - docker

install:
  - pip install -r requirements/dev.txt
#- curl https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy | sudo tee /usr/bin/ecs-deploy

#script:
#- python app/manage.py test

before_install:
- openssl aes-256-cbc -K $encrypted_8a111481f0c7_key -iv $encrypted_8a111481f0c7_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- chmod +x .bin/docker.sh

after_success:
  - .bin/docker.sh
