sudo: required
dist: xenial
language: python
python:
- 3.7.2
services:
- docker
#install:
#- curl https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy | sudo tee /usr/bin/ecs-deploy
#- sudo chmod +x /usr/bin/ecs-deploy
#- pip install -r requirements/base.txt
#script:
#- python app/manage.py test

before_install:
- openssl aes-256-cbc -K $encrypted_8a111481f0c7_key -iv $encrypted_8a111481f0c7_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar

after_success:
  - bash .bin/docker.sh
