sudo: required

dist: xenial

language: python

python:
  - 3.7.2

services:
  - docker

install:
  - pip install -r requirements/base.txt

before_install:
- openssl aes-256-cbc -K $encrypted_8a111481f0c7_key -iv $encrypted_8a111481f0c7_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- chmod +x .bin/docker.sh

after_success:
  - .bin/docker.sh
