FROM       python:3.7.2-slim
MAINTAINER gs2dang07@gmail.com

ENV        DJANGO_SETTINGS_MODULE config.settings.production
ENV        LAN                    C.UTF-8

RUN        apt-get -y -qq update
RUN        apt-get -y -qq dist-upgrade
RUN        apt-get -y install supervisor nginx && \
           pip install gunicorn

COPY       requirements/base.txt    /tmp/requirements.txt
RUN        pip install -r /tmp/requirements.txt
