# Generated by Django 2.1.4 on 2019-01-26 15:10

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20190125_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=20, validators=[members.models.nickname_length_validator], verbose_name='별명'),
        ),
    ]
