# Generated by Django 2.1.5 on 2019-03-04 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '댓글', 'verbose_name_plural': '댓글'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id'], 'verbose_name': '포스트', 'verbose_name_plural': '포스트'},
        ),
        migrations.AlterModelOptions(
            name='postlike',
            options={'verbose_name': '좋아요', 'verbose_name_plural': '좋아요'},
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='modified',
        ),
        migrations.AddField(
            model_name='postlike',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
